### PR TITLE
upgraded libraries - dropwizard etc

### PR DESCRIPTION
**Pull request by shashankg**
Hi,

I have upgraded the library with latest dropwizard, junit and apache commons. I need to use this for some project. Please review, merge and release.

Thanks
Shashank

### CODE REVIEW

**Comment by shashankg** [comment]
@minisu - please have a look at the pull request.

**Comment by minisu** [comment]
Hi, sorry for the wait!

Does it have to compile to Java 8? That prevents anyone on older Java versions to use this.

Isn't `commons-lang:3.4` already provided for us by dropwizard-configuration?

**Comment by shashankg** [comment]
I have removed common-lang explicit dependency and moved the compile version to java 7. It would be compatible with java 7 also.

**Comment by minisu** [comment]
Great!

**Pull request merged**
